In [1]:
import numpy as np

In [2]:
myarr=np.array([[2,1,32,4,5]],np.int8)    # 1st way to make numpy array

In [3]:
myarr[0,0]      # 0 row and 5 columns are available

2

In [4]:
myarr.shape

(1, 5)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0,4]=99

In [7]:
myarr

array([[ 2,  1, 32,  4, 99]], dtype=int8)

In [8]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [9]:
listarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(4, 3)

In [12]:
listarray.size

12

In [13]:
obj=np.array({23,3,213,223}) # this is objects

In [14]:
obj

array({3, 23, 213, 223}, dtype=object)

In [15]:
zeros=np.zeros((3,6)) # make zeros with 3 arrays

In [16]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
rng=np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace=np.linspace(3,46,10)  # 3 means 3 sa start 46 means 46 pa end  10 means k 10 elements print kare with equal space between them

In [20]:
lspace

array([ 3.        ,  7.77777778, 12.55555556, 17.33333333, 22.11111111,
       26.88888889, 31.66666667, 36.44444444, 41.22222222, 46.        ])

In [37]:

# Eduraka
# import sys
# size=getsizeof(myarr)
# size

a=np.array([(1,2,3),(3,4,5)])
print(a.sum(axis=1))
  
 # print(a.sum(axis=0))

 

[ 6 12]
